version: '3'

vars:
    COMPILER: latexmk
    JOBNAME: Assignment 1

tasks:
    compile:graphics:
        dir: ./src/
        vars:
            FLAGS: -pdf
            INPUT_DIR: content/figures
            OUTPUT_DIR: content/figures
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}              \
                -output-directory="./{{ .OUTPUT_DIR }}" \
                {{ .INPUT_DIR }}/exercise-1.2-2-graph.tikz
            - |
              {{ .COMPILER }} {{ .FLAGS }}              \
                -output-directory="./{{ .OUTPUT_DIR }}" \
                {{ .INPUT_DIR }}/exercise-2.1-1-sorting.tikz
    
    cleanup:
        vars:
            FLAGS: -c
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} -jobname="{{ .JOBNAME }}"

    build:
        dir: ./src/
        deps: [compile:graphics]
        vars:
            FLAGS: -pdf
            ENTRYPOINT: main.tex
            
            OUTPUT_DIR: ..
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}            \
              -jobname="{{ .JOBNAME }}"               \
              -output-directory="./{{ .OUTPUT_DIR }}" \
              {{ .ENTRYPOINT }}
    
    merge:
        vars:
            COMPILER: latexpand
            FLAGS: --keep-comments --verbose
            ENTRYPOINT: main.tex
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} \
              -output="{{ .JOBNAME }}.tex" \
              {{ .ENTRYPOINT }}
              
