version: '3'

vars:
    COMPILER: latexmk
    JOBNAME: Homework 3

tasks:
    graphics:convert:
        dir: ./src/assets/
        deps:
            - task: graphic:convert
              vars: { SRC: 'problem-12-pic-original.bmp', DEST: 'problem-12-pic-original.jpg' }
            - task: graphic:convert
              vars: { SRC: 'problem-12-pic-cbc.bmp', DEST: 'problem-12-pic-cbc.jpg' }
            - task: graphic:convert
              vars: { SRC: 'problem-12-pic-ecb.bmp', DEST: 'problem-12-pic-ecb.jpg' }

    cleanup:
        vars:
            FLAGS: -c
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} -jobname="{{ .JOBNAME }}"

    build:
        dir: ./src/
        deps: [graphics:convert]
        vars:
            FLAGS: -pdf
            ENTRYPOINT: main.tex
            
            OUTPUT_DIR: ..
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}            \
              -jobname="{{ .JOBNAME }}"               \
              -output-directory="./{{ .OUTPUT_DIR }}" \
              {{ .ENTRYPOINT }}
    
    merge:
        vars:
            COMPILER: latexpand
            FLAGS: --keep-comments --verbose
            ENTRYPOINT: main.tex
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} \
              -output="{{ .JOBNAME }}.tex" \
              {{ .ENTRYPOINT }}
              
    graphic:convert:
        internal: true
        dir: ./src/assets/
        requires:
            vars: [SRC, DEST]
        cmds:
            - magick -define bmp:ignore-filesize=true {{ .SRC }} {{ .DEST }}
